language: perl
dist: trusty
git:
    depth: 5

perl:
    - "5.26"

# GSL_CURRENT should always point to the version we build the CPAN dist with
env:
    global:
        - CCACHE_CPP2=1
        - CC="ccache clang"
        - GSL_CURRENT=2.5
        - GSL_INST_DIR=/tmp
        - GSL_SRC_DIR=/tmp/src
        - DIST_DIR=/tmp
    matrix:
        - GSL=2.5

addons:
  apt:
    packages:
      # - libgsl0-dev # this is 1.16 on trusty
      - gdb
      - swig2.0
      - texinfo

before_install: ./_travis/before_install.sh

# Add verbosity for debugging
install:
    - PKG_CONFIG_PATH=${GSL_INST_DIR}/gsl-$GSL/lib/pkgconfig PATH=${GSL_INST_DIR}/gsl-${GSL_CURRENT}/bin:$PATH cpanm --installdeps --notest --verbose .
    - cpanm --verbose --notest --skip-satisfied App::ReportPrereqs

before_script:
    - ulimit -c unlimited -S       # enable core dumps

script:
    - export LD_LIBRARY_PATH=${GSL_INST_DIR}/gsl-$GSL/lib
    - export PATH=${GSL_INST_DIR}/gsl-$GSL/bin:$PATH
    - cd /tmp
    - echo "Done!"

